name: Daily Xtream Codes Extraction

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Create results directory
      run: mkdir -p results
      
    - name: Run extraction
      run: node src/index.js
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        
    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Actions"
        git add results/
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add daily extraction results for $(date +'%Y-%m-%d')"
          git push
        fi
