name: Daily Xtream Codes Extraction

on:
  schedule:
    # Run every day at 01:00 AM UTC
    - cron: '0 1 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  extract:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Create results directory
      run: mkdir -p results
      
    - name: Run extraction
      run: node src/index.js
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        NODE_ENV: production
        
    - name: Check if results exist
      id: check_results
      run: |
        if [ -n "$(ls -A results/ 2>/dev/null)" ]; then
          echo "results_exists=true" >> $GITHUB_OUTPUT
        else
          echo "results_exists=false" >> $GITHUB_OUTPUT
          echo "No results files found"
        fi
        
    - name: Commit and push if changes exist
      if: steps.check_results.outputs.results_exists == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add results/
        git commit -m "Add daily extraction results for $(date +'%Y-%m-%d')"
        git push
